repos:
  # Enforce end of files, remove trailing whitespaces
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]

      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [ python ]

      - id: pytest
        stages: [push]
        types: [python]
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
