version: "3.8"

services:
  exporter:
    image: sheyabernstein/npm-influx-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:-npm-stats}-exporter
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./npm-logs:/app/data/logs
      - ./data/geolite:/app/data/geolite
      # - ./data/monitors:/app/data/monitors
    depends_on:
      - geoipupdate

  geoipupdate:
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-npm-stats}-geoipupdate
    environment:
      GEOIPUPDATE_ACCOUNT_ID: $GEOIPUPDATE_ACCOUNT_ID
      GEOIPUPDATE_LICENSE_KEY: $GEOIPUPDATE_LICENSE_KEY
      GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
      GEOIPUPDATE_FREQUENCY: ${GEOIPUPDATE_FREQUENCY:-24}
    volumes:
      - ./data/geolite:/usr/share/GeoIP
