name: Build, Lint and Test

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: |
        docker build -t npm-influx-exporter --target ci-cd .

    - name: Lint
      run: |
        docker run npm-influx-exporter ruff .

    - name: Test
      run: |
        docker run npm-influx-exporter pytest
