name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Build, Lint and Test"]
    types:
      - completed

env:
  IMAGE_NAME: npm-influx-exporter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'refs/tags/v') && github.ref =~ '^refs/tags/v[0-9]+.[0-9]+.[0-9]+$'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
           VERSION=${{ github.ref_name }}
           PUBLISH_VERSION=${VERSION:1}
           echo "Version to publish is ${PUBLISH_VERSION}"

           docker build \
             --push \
             --target production \
             --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
             --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${PUBLISH_VERSION} \
             .
