name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: 360
          days-before-issue-close: 60
          stale-issue-message: "This issue is being marked as stale due to no recent activity. It will be closed in 60 days."
          close-issue-message: "This issue has been closed due to no recent activity."
          days-before-pr-stale: 180
          days-before-pr-close: 60
          stale-pr-message: "This PR is being marked as stale due to no recent activity. It will be closed in 60 days."
          close-pr-message: "This PR has been closed due to no recent activity."
